name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.103'
    - name: Build
      run: |
        dotnet build tiny-fp.sln
    - name: Test
      run: |
        dotnet test tiny-fp.sln
  